import Souq_DataCollectors_configuration as DataCollectors_Configuration
import Souq.CONSTANTS as CONSTANTS
import product_info_storage
import Storage_config
import completed_queue
import Souq_DataCollectors_configuration as config
from Souq_DataCollectors_configuration import SOUQ_CATEGORY_LIST
import fnmatch
import response_getter
from print_exception import print_exception
from Souq.file_operations import file_to_list,file_to_dictionary,file_to_set,append_to_file,dictionary_to_file,list_to_file
import response_getter
import os
import sys
#import Souq.CONSTANTS as CONSTANTS
import Souq.Write_contants_file
from Souq_DataCollectors_configuration import SOUQ_HIRERACHY_ROOT_FOLDER
from datetime import datetime
import re
import Queue
import threading
from Souq.file_operations import create_project_dir, file_to_list
from Souq.product_parsers.Beauty_product_parser import *
import response_getter
from Souq.product_parsers.Gaming_product_parser import *
from Souq.product_parsers.Sports_and_Fitness_product_parser import *
from Souq.product_parsers.Health_and_Personal_Care_product_parser import *
import fnmatch
#from Souq.config import CATEGORY_LIST
from Souq_DataCollectors_configuration import SOUQ_CATEGORY_LIST, START_URL_COLLECTION, START_INFO_COLLECTION
import time
import json
#import DataCollectors_Configuration
from datetime import date
import Queue
import re
import time
from bs4 import BeautifulSoup, NavigableString
from threading import Thread
from print_exception import print_exception
import Souq.CONSTANTS
from product_info_storage import store
import Souq.path_CONSTANTS
import uuid
import multiprocessing
from collections import OrderedDict

from Souq.product_parsers.Apparel_Shoes_and_Accessories_product_parser import ProductDetails as Apparel_Shoes_and_Accessories_ProductDetails
from Souq.product_parsers.Art_Crafts_and_Collectibles_product_parser import ProductDetails as Art_Crafts_and_Collectibles_ProductDetails
from Souq.product_parsers.Baby_product_parser import ProductDetails as Baby_ProductDetails
from Souq.product_parsers.Beauty_product_parser import ProductDetails as Beauty_ProductDetails
from Souq.product_parsers.Bed_and_Bath_product_parser import ProductDetails as Bed_and_Bath_ProductDetails
from Souq.product_parsers.Books_product_parser import ProductDetails as Books_ProductDetails
from Souq.product_parsers.Cameras_product_parser import ProductDetails as Cameras_ProductDetails
from Souq.product_parsers.Coins_Stamps_and_Paper_money_product_parser import ProductDetails as Coins_Stamps_and_Paper_money_ProductDetails
from Souq.product_parsers.Computers_IT_and_Networking_product_parser import ProductDetails as Computers_IT_and_Networking_ProductDetails
from Souq.product_parsers.Electronics_product_parser import ProductDetails as Electronics_ProductDetails
from Souq.product_parsers.Eyewear_and_Optics_product_parser import ProductDetails as Eyewear_and_Optics_ProductDetails
from Souq.product_parsers.Furniture_product_parser import ProductDetails as Furniture_ProductDetails
from Souq.product_parsers.Gaming_product_parser import ProductDetails as Gaming_ProductDetails
from Souq.product_parsers.Garden_and_Outdoor_product_parser import ProductDetails as Garden_and_Outdoor_ProductDetails
from Souq.product_parsers.Grocery_Food_and_Beverages_product_parser import ProductDetails as Grocery_Food_and_Beverages_ProductDetails
from Souq.product_parsers.Health_and_Personal_Care_product_parser import ProductDetails as Health_and_Personal_Care_ProductDetails
from Souq.product_parsers.Home_Appliances_product_parser import ProductDetails as Home_Appliances_ProductDetails
from Souq.product_parsers.Home_Decor_and_Furniture_product_parser import ProductDetails as Home_Decor_and_Furniture_ProductDetails
from Souq.product_parsers.Jewelry_and_Accessories_product_parser import ProductDetails as Jewelry_and_Accessories_ProductDetails
from Souq.product_parsers.Kitchen_and_Home_Supplies_product_parser import ProductDetails as Kitchen_and_Home_Supplies_ProductDetails
from Souq.product_parsers.Kitchen_Appliances_product_parser import ProductDetails as Kitchen_Appliances_ProductDetails
from Souq.product_parsers.Mobile_Phones_Tablets_and_Accessories_product_parser import ProductDetails as Mobile_Phones_Tablets_and_Accessories_ProductDetails
from Souq.product_parsers.Music_and_Movies_product_parser import ProductDetails as Music_and_Movies_ProductDetails
from Souq.product_parsers.Office_Products_and_Supplies_product_parser import ProductDetails as Office_Products_and_Supplies_ProductDetails
from Souq.product_parsers.Perfumes_and_Fragrances_product_parser import ProductDetails as Perfumes_and_Fragrances_ProductDetails
from Souq.product_parsers.Pet_Food_and_Supplies_product_parser import ProductDetails as Pet_Food_and_Supplies_ProductDetails
from Souq.product_parsers.Sports_and_Fitness_product_parser import ProductDetails as Sports_and_Fitness_ProductDetails
from Souq.product_parsers.Tools_and_Home_Improvements_product_parser import ProductDetails as Tools_and_Home_Improvements_ProductDetails
from Souq.product_parsers.Toys_product_parser import ProductDetails as Toys_ProductDetails
from Souq.product_parsers.Vehicle_Parts_and_Accessories_product_parser import ProductDetails as Vehicle_Parts_and_Accessories_ProductDetails
from Souq.product_parsers.Vouchers_and_Tickets_product_parser import ProductDetails as Vouchers_and_Tickets_ProductDetails
from Souq.product_parsers.Wearable_Technology_Devices_product_parser import ProductDetails as Wearable_Technology_Devices_ProductDetails


from Souq.product_info_collectors import Apparel_Shoes_and_Accessories_info_collector, Art_Crafts_and_Collectibles_info_collector, Baby_info_collector, Beauty_info_collector, Bed_and_Bath_info_collector, Books_info_collector, Cameras_info_collector, Coins_Stamps_and_Paper_money_info_collector, Computers_IT_and_Networking_info_collector, Electronics_info_collector, Eyewear_and_Optics_info_collector, Furniture_info_collector, Gaming_info_collector, Garden_and_Outdoor_info_collector, Grocery_Food_and_Beverages_info_collector, Health_and_Personal_Care_info_collector, Home_Appliances_info_collector, Home_Decor_and_Furniture_info_collector, Jewelry_and_Accessories_info_collector, Kitchen_and_Home_Supplies_info_collector, Kitchen_Appliances_info_collector, Mobile_Phones_Tablets_and_Accessories_info_collector, Music_and_Movies_info_collector, Office_Products_and_Supplies_info_collector, Perfumes_and_Fragrances_info_collector, Pet_Food_and_Supplies_info_collector, Sports_and_Fitness_info_collector, Tools_and_Home_Improvements_info_collector, Toys_info_collector, Vehicle_Parts_and_Accessories_info_collector, Vouchers_and_Tickets_info_collector, Wearable_Technology_Devices_info_collector
from Souq.scrappers import Apparel_Shoes_and_Accessories_scrape_urls, Art_Crafts_and_Collectibles_scrape_urls, Baby_scrape_urls, Beauty_scrape_urls, Bed_and_Bath_scrape_urls, Books_scrape_urls, Cameras_scrape_urls,  Coins_Stamps_and_Paper_money_scrape_urls, Computers_IT_and_Networking_scrape_urls, Electronics_scrape_urls,Eyewear_and_Optics_scrape_urls, Furniture_scrape_urls, Gaming_scrape_urls, Garden_and_Outdoor_scrape_urls,Grocery_Food_and_Beverages_scrape_urls, Health_and_Personal_Care_scrape_urls, Home_Appliances_scrape_urls,Home_Decor_and_Furniture_scrape_urls, Jewelry_and_Accessories_scrape_urls, Kitchen_and_Home_Supplies_scrape_urls,Kitchen_Appliances_scrape_urls, Mobile_Phones_Tablets_and_Accessories_scrape_urls, Music_and_Movies_scrape_urls,Office_Products_and_Supplies_scrape_urls, Perfumes_and_Fragrances_scrape_urls, Pet_Food_and_Supplies_scrape_urls,Sports_and_Fitness_scrape_urls, Tools_and_Home_Improvements_scrape_urls, Toys_scrape_urls, Vehicle_Parts_and_Accessories_scrape_urls, Vouchers_and_Tickets_scrape_urls, Wearable_Technology_Devices_scrape_urls