from Common.Souq_common_imports import *
Apparel_Shoes_and_Accessories_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Apparel_Shoes_and_Accessories/Apparel_Shoes_and_Accessories_link_queue.txt'
Apparel_Shoes_and_Accessories_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Apparel_Shoes_and_Accessories/Apparel_Shoes_and_Accessories_link_completed.txt'
Apparel_Shoes_and_Accessories_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Apparel_Shoes_and_Accessories/Apparel_Shoes_and_Accessories_link_completed.txt'

Art_Crafts_and_Collectibles_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Art_Crafts_and_Collectibles/Art_Crafts_and_Collectibles_link_queue.txt'
Art_Crafts_and_Collectibles_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Art_Crafts_and_Collectibles/Art_Crafts_and_Collectibles_link_completed.txt'
Art_Crafts_and_Collectibles_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Art_Crafts_and_Collectibles/Art_Crafts_and_Collectibles_link_completed.txt'

Baby_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Baby/Baby_link_queue.txt'
Baby_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Baby/Baby_link_completed.txt'
Baby_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Baby/Baby_link_completed.txt'

Beauty_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Beauty/Beauty_link_queue.txt'
Beauty_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Beauty/Beauty_link_completed.txt'
Beauty_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Beauty/Beauty_link_completed.txt'

Bed_and_Bath_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Bed_and_Bath/Bed_and_Bath_link_queue.txt'
Bed_and_Bath_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Bed_and_Bath/Bed_and_Bath_link_completed.txt'
Bed_and_Bath_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Bed_and_Bath/Bed_and_Bath_link_completed.txt'

Books_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Books/Books_link_queue.txt'
Books_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Books/Books_link_completed.txt'
Books_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Books/Books_link_completed.txt'

Cameras_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Cameras/Cameras_link_queue.txt'
Cameras_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Cameras/Cameras_link_completed.txt'
Cameras_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Cameras/Cameras_link_completed.txt'

Coins_Stamps_and_Paper_money_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Coins_Stamps_and_Paper_money/Coins_Stamps_and_Paper_money_link_queue.txt'
Coins_Stamps_and_Paper_money_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Coins_Stamps_and_Paper_money/Coins_Stamps_and_Paper_money_link_completed.txt'
Coins_Stamps_and_Paper_money_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Coins_Stamps_and_Paper_money/Coins_Stamps_and_Paper_money_link_completed.txt'

Computers_IT_and_Networking_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Computers_IT_and_Networking/Computers_IT_and_Networking_link_queue.txt'
Computers_IT_and_Networking_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Computers_IT_and_Networking/Computers_IT_and_Networking_link_completed.txt'
Computers_IT_and_Networking_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Computers_IT_and_Networking/Computers_IT_and_Networking_link_completed.txt'

Electronics_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Electronics/Electronics_link_queue.txt'
Electronics_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Electronics/Electronics_link_completed.txt'
Electronics_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Electronics/Electronics_link_completed.txt'

Eyewear_and_Optics_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Eyewear_and_Optics/Eyewear_and_Optics_link_queue.txt'
Eyewear_and_Optics_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Eyewear_and_Optics/Eyewear_and_Optics_link_completed.txt'
Eyewear_and_Optics_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Eyewear_and_Optics/Eyewear_and_Optics_link_completed.txt'

Furniture_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Furniture/Furniture_link_queue.txt'
Furniture_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Furniture/Furniture_link_completed.txt'
Furniture_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Furniture/Furniture_link_completed.txt'

Gaming_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Gaming/Gaming_link_queue.txt'
Gaming_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Gaming/Gaming_link_completed.txt'
Gaming_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Gaming/Gaming_link_completed.txt'

Garden_and_Outdoor_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Garden_and_Outdoor/Garden_and_Outdoor_link_queue.txt'
Garden_and_Outdoor_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Garden_and_Outdoor/Garden_and_Outdoor_link_completed.txt'
Garden_and_Outdoor_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Garden_and_Outdoor/Garden_and_Outdoor_link_completed.txt'

Grocery_Food_and_Beverages_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Grocery_Food_and_Beverages/Grocery_Food_and_Beverages_link_queue.txt'
Grocery_Food_and_Beverages_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Grocery_Food_and_Beverages/Grocery_Food_and_Beverages_link_completed.txt'
Grocery_Food_and_Beverages_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Grocery_Food_and_Beverages/Grocery_Food_and_Beverages_link_completed.txt'

Health_and_Personal_Care_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Health_and_Personal_Care/Health_and_Personal_Care_link_queue.txt'
Health_and_Personal_Care_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Health_and_Personal_Care/Health_and_Personal_Care_link_completed.txt'
Health_and_Personal_Care_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Health_and_Personal_Care/Health_and_Personal_Care_link_completed.txt'

Home_Appliances_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Home_Appliances/Home_Appliances_link_queue.txt'
Home_Appliances_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Home_Appliances/Home_Appliances_link_completed.txt'
Home_Appliances_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Home_Appliances/Home_Appliances_link_completed.txt'

Home_Decor_and_Furniture_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Home_Decor_and_Furniture/Home_Decor_and_Furniture_link_queue.txt'
Home_Decor_and_Furniture_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Home_Decor_and_Furniture/Home_Decor_and_Furniture_link_completed.txt'
Home_Decor_and_Furniture_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Home_Decor_and_Furniture/Home_Decor_and_Furniture_link_completed.txt'

Jewelry_and_Accessories_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Jewelry_and_Accessories/Jewelry_and_Accessories_link_queue.txt'
Jewelry_and_Accessories_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Jewelry_and_Accessories/Jewelry_and_Accessories_link_completed.txt'
Jewelry_and_Accessories_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Jewelry_and_Accessories/Jewelry_and_Accessories_link_completed.txt'

Kitchen_and_Home_Supplies_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Kitchen_and_Home_Supplies/Kitchen_and_Home_Supplies_link_queue.txt'
Kitchen_and_Home_Supplies_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Kitchen_and_Home_Supplies/Kitchen_and_Home_Supplies_link_completed.txt'
Kitchen_and_Home_Supplies_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Kitchen_and_Home_Supplies/Kitchen_and_Home_Supplies_link_completed.txt'

Kitchen_Appliances_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Kitchen_Appliances/Kitchen_Appliances_link_queue.txt'
Kitchen_Appliances_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Kitchen_Appliances/Kitchen_Appliances_link_completed.txt'
Kitchen_Appliances_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Kitchen_Appliances/Kitchen_Appliances_link_completed.txt'

Mobile_Phones_Tablets_and_Accessories_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Mobile_Phones_Tablets_and_Accessories/Mobile_Phones_Tablets_and_Accessories_link_queue.txt'
Mobile_Phones_Tablets_and_Accessories_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Mobile_Phones_Tablets_and_Accessories/Mobile_Phones_Tablets_and_Accessories_link_completed.txt'
Mobile_Phones_Tablets_and_Accessories_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Mobile_Phones_Tablets_and_Accessories/Mobile_Phones_Tablets_and_Accessories_link_completed.txt'

Music_and_Movies_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Music_and_Movies/Music_and_Movies_link_queue.txt'
Music_and_Movies_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Music_and_Movies/Music_and_Movies_link_completed.txt'
Music_and_Movies_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Music_and_Movies/Music_and_Movies_link_completed.txt'

Office_Products_and_Supplies_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Office_Products_and_Supplies/Office_Products_and_Supplies_link_queue.txt'
Office_Products_and_Supplies_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Office_Products_and_Supplies/Office_Products_and_Supplies_link_completed.txt'
Office_Products_and_Supplies_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Office_Products_and_Supplies/Office_Products_and_Supplies_link_completed.txt'

Perfumes_and_Fragrances_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Perfumes_and_Fragrances/Perfumes_and_Fragrances_link_queue.txt'
Perfumes_and_Fragrances_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Perfumes_and_Fragrances/Perfumes_and_Fragrances_link_completed.txt'
Perfumes_and_Fragrances_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Perfumes_and_Fragrances/Perfumes_and_Fragrances_link_completed.txt'

Pet_Food_and_Supplies_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Pet_Food_and_Supplies/Pet_Food_and_Supplies_link_queue.txt'
Pet_Food_and_Supplies_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Pet_Food_and_Supplies/Pet_Food_and_Supplies_link_completed.txt'
Pet_Food_and_Supplies_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Pet_Food_and_Supplies/Pet_Food_and_Supplies_link_completed.txt'

Sports_and_Fitness_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Sports_and_Fitness/Sports_and_Fitness_link_queue.txt'
Sports_and_Fitness_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Sports_and_Fitness/Sports_and_Fitness_link_completed.txt'
Sports_and_Fitness_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Sports_and_Fitness/Sports_and_Fitness_link_completed.txt'

Tools_and_Home_Improvements_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Tools_and_Home_Improvements/Tools_and_Home_Improvements_link_queue.txt'
Tools_and_Home_Improvements_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Tools_and_Home_Improvements/Tools_and_Home_Improvements_link_completed.txt'
Tools_and_Home_Improvements_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Tools_and_Home_Improvements/Tools_and_Home_Improvements_link_completed.txt'

Toys_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Toys/Toys_link_queue.txt'
Toys_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Toys/Toys_link_completed.txt'
Toys_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Toys/Toys_link_completed.txt'

Vehicle_Parts_and_Accessories_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Vehicle_Parts_and_Accessories/Vehicle_Parts_and_Accessories_link_queue.txt'
Vehicle_Parts_and_Accessories_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Vehicle_Parts_and_Accessories/Vehicle_Parts_and_Accessories_link_completed.txt'
Vehicle_Parts_and_Accessories_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Vehicle_Parts_and_Accessories/Vehicle_Parts_and_Accessories_link_completed.txt'

Vouchers_and_Tickets_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Vouchers_and_Tickets/Vouchers_and_Tickets_link_queue.txt'
Vouchers_and_Tickets_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Vouchers_and_Tickets/Vouchers_and_Tickets_link_completed.txt'
Vouchers_and_Tickets_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Vouchers_and_Tickets/Vouchers_and_Tickets_link_completed.txt'

Wearable_Technology_Devices_QUEUE_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Wearable_Technology_Devices/Wearable_Technology_Devices_link_queue.txt'
Wearable_Technology_Devices_COMPLETED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Wearable_Technology_Devices/Wearable_Technology_Devices_link_completed.txt'
Wearable_Technology_Devices_SKIPPED_FILE = SOUQ_HIRERACHY_ROOT_FOLDER+'/Wearable_Technology_Devices/Wearable_Technology_Devices_link_completed.txt'

